### ISSUE TITLE
Missing Turrets

### ISSUE THREAD

**Issue by Armilia81** [zuoranartemwing/MindustryExpansion#30]
Theirs only Two Turrets that appear on your Mod and the others didn't Appeared and that is Heal Bomber and Rail Gun
![Screenshot_2024-01-22-14-11-39-64](https://github.com/zuoranartemwing/TurretExpansion/assets/157344911/5e10b3df-5966-48e0-8b37-191188d895aa)

**Comment by zuoranartemwing** [comment]
We are still working on that, And because My Other mod is still Experimental and Under Working and need More Optimize and more Stabilizer For Real Research and For Champaign Mode, and we are working On New Mod named _"expansion foundation"_ And _"Unit Expansion"_ So you have to be patient to use our turret in campaign mode

- Founder Turret Expansion
**@zuoranartemwing **

**Comment by zuoranartemwing** [comment]
We are still working on that, And because My Other mod is still Experimental and Under Working and need More Optimize and more Stabilizer For Real Research and For Champaign Mode, and we are working On New Mod named _"expansion foundation"_ And _"Unit Expansion"_ So you have to be patient to use our turret in campaign mode

- Founder Turret Expansion
**@zuoranartemwing **

Anyway thanks For Give Feedback to our smal team we will make update if we are have enough time
